name: c-linter
on:
  pull_request:
    branches: [main, dev]
    paths: ["**.c", "**.h"]
  push:
    branches: [main, dev]
    paths: ["**.c", "**.h"]

jobs:
  c-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file # Use .clang-format file
          tidy-checks: '' # Use .clang-tidy file
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
      - name: Fail Fast
        if: steps.linter.outputs.clang-tidy-checks-failed > 0
        run: exit 1
